### ISSUE TITLE
Point2 vs Point2D?

### ISSUE THREAD

**Issue by amacneil** [foxglove/message-schemas#20]
These feel unnecessarily abbreviated to me:

* Point2
* Point3
* Vector2
* Vector3

Is there some prior art we are copying for consistency? Or should we add an extra `D` to each of them?

**Comment by jhurliman** [comment]
In Eigen, a `Vector2d` is two 64-bit doubles and a `Vector2f` is two 32-bit floats. Is the idea of adding a D to signify that these are all double precision?

**Comment by jtbandes** [comment]
> Is the idea of adding a D to signify that these are all double precision?

I’m pretty sure Adrian meant the D to stand for “dimensional”?

Thought experiment: if we wanted to add an integer version of a point (for pixel/grid coordinates), what would we call it?

**Comment by amacneil** [comment]
If there is some prior art we are copying that's fine... just looks weird to my untrained eye.

I notice that ROS has both `Pose2D` and `Vector3`, so I guess that's not helpful.

> In Eigen, a Vector2d is two 64-bit doubles and a Vector2f is two 32-bit floats. Is the idea of adding a D to signify that these are all double precision?

😭 that's terrible - if I saw `Vector2d` out of context I would expect it to be a two dimensional vector, not a double precision 3 dimensional vector

> Thought experiment: if we wanted to add an integer version of a point (for pixel/grid coordinates), what would we call it?

`Point2I` 🙈

**Comment by jhurliman** [comment]
Vector3 prior art: https://docs.unity3d.com/ScriptReference/Vector3.html

**Comment by amacneil** [comment]
Looking at the Unity docs you linked, `Vector3` is kind of an outlier...

<img width="161" alt="image" src="https://user-images.githubusercontent.com/637671/167282711-4edeb60a-25ec-4fbd-84a4-1e62f5a56d0f.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/637671/167282715-f60fe727-38d5-403d-9288-e207cf09b11f.png">
<img width="261" alt="image" src="https://user-images.githubusercontent.com/637671/167282734-f4442660-88b6-4391-a015-e59d2fa9915a.png">

From googling, Vector3 does seem pretty common across many languages/frameworks. But those same frameworks also use 2D/3D for other types. All hope is gone.
