### ISSUE TITLE
Rename repo to message-schemas

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/message-schemas#7]
**Description**
https://github.com/foxglove/ros-message-schemas/blob/6807f46716017a0461656f56dde5274943c7d528/LocationFix.proto

This repo contains a non-ros proto file which corresponds to our documented schema: https://foxglove.dev/docs/messages/location-fix

We should rename this repo to `message-schemas` and have to top level folders under proto: `ros` and `foxglove` where we store the two variants.

**Comment by defunctzombie** [comment]
@jtbandes thoughts?

**Comment by jtbandes** [comment]
Ok. It seems useful to have both the JSON Schema and .proto definitions available for our custom schemas as well as the ROS schemas. Don't think those will be able to share any of the same generation scripts (since the script uses parsed .msg files as input) but we could keep them in the same repo.

**Comment by defunctzombie** [comment]
Renamed
